
defaults:
  - model/common@model.encoder: conv
  - model/common@model.decoder: conv
  - loggers@meta: meta
  - loggers@hydra: hydra
  - loggers@lightning: lightning
  - loggers@wandb: wandb
hydra:
  job:
    chdir: False

losses:
  loss_type: [MSELoss,BVAEKLLoss]
  beta: 0.0001

model:
  ckpt_path: test.ckpt/epoch=0-step=150.ckpt

wandb:
  enabled: True

seed: 42 

dataset:
  dataset: celeba_hq
  root: ./data
  batch_size: 64
  num_workers: 10
  transform:
    - type: ToTensor
    - type: Resize
      size: ${model.encoder.img_size}
  mode: [compose]

vis:
  visualize_batch: 25
  visualize_nrow: 5
  save_dir: ./output/vis

trainer:
  limit_train_batches: 10000
  max_epochs: 50
  
optimizer:
  lr: 0.0001