
defaults:
  - model/common@model.encoder: conv
  - model/common@model.decoder: conv
  - wandb: tiny-bvae

hydra:
  job:
    chdir: False

model:
  ckpt_path: 

wandb:
  enabled: True

seed: 42 

dataset:
  dataset: celeba_hq
  root: ./data
  batch_size: 64
  num_workers: 10
  transform:
    - type: ToTensor
    - type: Resize
      size: ${model.encoder.img_size}
  mode: [compose]